<?php
# This file was generated by MediaWiki installer but is now managed manually.
# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Database settings
$wgDBtype = "mysql";
$wgDBserver = getenv('MW_DB_HOST') ?: "db";
$wgDBname = getenv('MW_DB_NAME') ?: "mediawiki";
$wgDBuser = getenv('MW_DB_USER') ?: "root";
$wgDBpassword = getenv('MW_DB_PASS') ?: "mediawiki";

# MySQL specific settings
$wgDBprefix = "";
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Site configuration
$wgSitename = getenv('MW_SITENAME') ?: "My Wiki";
$wgMetaNamespace = "My_Wiki";

## Server URLs and paths
$wgServer = getenv('MW_SITE_SERVER') ?: "http://localhost";
$wgScriptPath = "/w";
$wgResourceBasePath = $wgScriptPath;

## Nice URLs configuration
$wgArticlePath = "/$1";
$wgUsePathInfo = true;

## Security and permissions
# Generate secure random keys if not set via environment
$wgSecretKey = getenv('MW_SECRET_KEY') ?: bin2hex(random_bytes(32));
$wgUpgradeKey = getenv('MW_UPGRADE_KEY') ?: bin2hex(random_bytes(16));

## Administrator
$wgEmergencyContact = getenv('MW_EMERGENCY_CONTACT') ?: "admin@example.com";
$wgPasswordSender = getenv('MW_PASSWORD_SENDER') ?: "admin@example.com";

## Language and locale
$wgLanguageCode = getenv('MW_WIKI_LANG') ?: "en";

## File uploads
$wgEnableUploads = true;
$wgUploadDirectory = "/mediawiki/images";
$wgUploadPath = "/images";
$wgFileExtensions = array_merge( $wgFileExtensions, [
	'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'
]);

## Skins
wfLoadSkin( 'Vector' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'MinervaNeue' );
$wgDefaultSkin = "vector";

## Performance and caching
$wgCacheDirectory = "/tmp";
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## Extensions
# Add your extensions here
# wfLoadExtension( 'ExtensionName' );

## Memory and execution limits
ini_set( 'memory_limit', '512M' );
$wgMaxShellMemory = 512000;

## Logo (uncomment and set path to your logo)
# $wgLogos = [
#     '1x' => "$wgResourceBasePath/resources/assets/wiki.png",
# ];

## Include custom settings template
$customSettingsFile = __DIR__ . '/SettingsTemplate.php';
if ( file_exists( $customSettingsFile ) ) {
	include_once $customSettingsFile;
}